### ISSUE TITLE
What is the period time between failed reconciler errors

### ISSUE THREAD

**Issue by nyikesda** [vertica/vertica-kubernetes#160]
In our product we have to restart the whole vertica cluster because of the internode encryption: https://www.vertica.com/docs/11.0.x/HTML/Content/Authoring/Security/TLS/ControlChannelSpreadTLS.htm?tocpath=Security%20and%20Authentication%7CInternode%20TLS%7C_____1

It is implemented in our vertica container to call `admintools --tool stop_db` after the necessary steps and we will wait for the operator to start the db again.

During this period the operator could not call "vsql -c select 1" of course, but sometimes the operator wait about 20 minutes in idle state  before the `admintools -t start_db` command.

I have attached the whole log, the ~20 minutes idle state is between:
2022-02-21T12:24:30.679Z
2022-02-21T12:41:10.680Z

[vertica_operator_logs.txt](https://github.com/vertica/vertica-kubernetes/files/8125015/vertica_operator_logs.txt)

**Comment by spilchen** [comment]
You need to give the operator a reason to go through its reconcile loop.  It has watches on the VerticaDB object and its child objects (sts, svc, pod, etc.), but if those don't change then it will just check at the next timeout, which you saw can be as much as 20 minutes.

We have the `spec.autoRestartVertica` parameter if you don't want the operator interfere with a manual shutdown.  So one approach is:
- update the CR to set `.spec.autoRestartVertica: false`
- call `admintools --tool stop_db` manually
- update the CR to set `.spec.autoRestartVertica: true`

The reconcile loop will kick in when you do the update to autoRestartVertica.  So that should force the operator to call start_db quicker.

We are thinking about having an option to stop subclusters, so that is another approach you can do in the future.

**Comment by nyikesda** [comment]
Thanks, in this case this ticket can be closed.
