### ISSUE TITLE
[docker images] Why is Vertica installed on AlmaLinux 8 and then transferred to Rocky Linux 9?

### ISSUE THREAD

**Issue by dk-tgz** [vertica/vertica-kubernetes#830]
Hello,

I have noticed that in the Dockerfile, Vertica is initially installed on AlmaLinux 8 and then the some directories are moved to a Rocky Linux 9 base image. Could you please explain the reasoning behind this approach? Here is the relevant part of the Dockerfile for reference:
https://github.com/vertica/vertica-kubernetes/blob/main/docker-vertica-v2/Dockerfile
https://github.com/vertica/vertica-kubernetes/blob/main/docker-vertica/Dockerfile

I understand that the extra step clears up the image a bit, but I don't understand why it's a different system in a different version, that  may not be fully compatible with each other at some point. It seems to me that in both cases it should be either on alma 8 or rocky 8 or 9.

Also, what is the difference between v2 and v1 docker-vertica images? From what I've read in commits, there is better support for OpenShift.

**Comment by jizhuoyu** [comment]
For the first question: This is no specific reason why we must use almalinux in the first stage of the Dockerfile. We use almalinux to ensure max compatibility with vertica build and release process. We use rockylinux as the base OS because it is bug-for-bug compatible with RHEL distros, which are more commonly used for enterprise deployments. There should not be concerns for compatibility between almalinux and rockylinux, because in the final stage of the Dockerfile we only copy vertica-related files from the first stage.

For the second question: The v2 image is compatible with vcluster, which is the new cluster management tool, replacing legacy admintools, while the v1 image is compatible with admintools.
